const c=document.getElementById('c'),x=c.getContext('2d'),wrap=document.getElementById('wrap');let im=new Image(),ready=false,zoom=1,mode='select',color='#e83ac5',stroke=4,items=[],current=null;
let key=localStorage.getItem('rf_key')||'',proxy=localStorage.getItem('rf_proxy')||'';document.getElementById('key').value=key;document.getElementById('proxy').value=proxy;
im.onload=()=>{ready=true;fit()};im.onerror=()=>{ready=false; document.getElementById('load').classList.add('hidden'); modal('벽 사진을 불러오지 못했습니다','spray wall.jpg 파일이 GitHub 저장소에 있는지 확인해 주세요.\n\n사진 파일은 다른 폴더가 아니라 index.html과 같은 위치에 올려주세요.');}; im.src='./spray%20wall.jpg';
function resize(){c.width=im.naturalWidth;c.height=im.naturalHeight;c.style.width=im.naturalWidth*zoom+'px';c.style.height=im.naturalHeight*zoom+'px';draw()}function fit(){if(!ready)return;zoom=Math.max(.4,Math.min(1.8,Math.min((wrap.clientWidth-35)/im.naturalWidth,(wrap.clientHeight-35)/im.naturalHeight)));document.getElementById('zs').value=zoom*100;document.getElementById('zt').textContent=Math.round(zoom*100)+'%';resize()}window.onresize=fit;
function setz(v){zoom=Math.max(.4,Math.min(1.8,v));document.getElementById('zs').value=zoom*100;document.getElementById('zt').textContent=Math.round(zoom*100)+'%';resize()}document.getElementById('zs').oninput=e=>setz(+e.target.value/100);document.getElementById('zm').onclick=()=>setz(zoom-.1);document.getElementById('zp').onclick=()=>setz(zoom+.1);document.getElementById('fit').onclick=fit;
document.getElementById('file').onchange=e=>{let f=e.target.files[0];if(!f)return;im.src=URL.createObjectURL(f);im.onload=()=>{items=[];current=null;fit();list()}};
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(q=>q.classList.remove('on'));b.classList.add('on');mode=b.dataset.mode});document.querySelectorAll('.colors button').forEach(b=>b.onclick=()=>{color=b.dataset.c;if(current){current.color=color;draw();list()}});document.getElementById('ss').oninput=e=>{stroke=+e.target.value;document.getElementById('st').textContent=stroke+'px';draw()};
document.getElementById('save').onclick=()=>{key=document.getElementById('key').value.trim();proxy=document.getElementById('proxy').value.trim().replace(/\/$/,'');localStorage.setItem('rf_key',key);localStorage.setItem('rf_proxy',proxy);document.getElementById('status').textContent=key||proxy?'AI 설정 적용됨':'AI 연결 전'};
function pt(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
c.oncontextmenu=e=>e.preventDefault();c.onpointerdown=async e=>{if(!ready)return;let p=pt(e);if(mode==='select'){current={points:[{x:Math.round(p.x),y:Math.round(p.y),positive:true}],mask:null,color,label:items.length<5?['Top','2','3','4','Start'][items.length]:String(items.length+1),visible:true};items.push(current);list();await infer(current)}else if(current){current.points.push({x:Math.round(p.x),y:Math.round(p.y),positive:mode==='add'});await infer(current)}};
function base64(){let q=document.createElement('canvas'),sc=Math.min(1,2200/im.naturalWidth);q.width=im.naturalWidth*sc;q.height=im.naturalHeight*sc;q.getContext('2d').drawImage(im,0,0,q.width,q.height);let b=q.toDataURL('image/jpeg',.9).split(',')[1];return{b,sc}}
async function infer(s){if(!key&&!proxy){modal('AI 연결이 필요합니다','왼쪽 AI 연결 영역에 Roboflow API Key 또는 Worker URL을 입력하고 AI 설정 적용을 눌러주세요.');return}document.getElementById('load').classList.remove('hidden');try{let z=base64();let pts=s.points.map(p=>({x:Math.round(p.x*z.sc),y:Math.round(p.y*z.sc),positive:p.positive}));let body={image:{type:'base64',value:z.b},prompts:[{points:pts}],format:'json',multimask_output:false};let u=proxy||'https://serverless.roboflow.com/sam3/visual_segment?api_key='+encodeURIComponent(key);let r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.detail||d.message||JSON.stringify(d));s.mask=parseMask(d,z.sc);if(!s.mask)throw Error('마스크를 받지 못했습니다. 홀드 내부를 다시 클릭해 주세요.');draw();list()}catch(e){console.error(e);modal('AI 처리 실패',e.message+'\n\n홀드 내부를 조금 더 정확히 클릭하거나 +/− 도구로 보정해 주세요.')}finally{document.getElementById('load').classList.add('hidden')}}
function parseMask(d,sc){let p=d?.prompt_results?.[0]?.predictions?.[0],m=p?.masks?.[0]||p?.masks||d?.masks?.[0];if(!Array.isArray(m)||!m.length)return null;if(Array.isArray(m[0])&&typeof m[0][0]==='number')return m.map(a=>({x:a[0]/sc,y:a[1]/sc}));if(Array.isArray(m[0])&&Array.isArray(m[0][0]))return m[0].map(a=>({x:a[0]/sc,y:a[1]/sc}));return null}
function rgba(h,a){let z=h.replace('#','');if(z.length===3)z=z.split('').map(q=>q+q).join('');return`rgba(${parseInt(z.slice(0,2),16)},${parseInt(z.slice(2,4),16)},${parseInt(z.slice(4,6),16)},${a})`}
function draw(){if(!ready)return;x.clearRect(0,0,c.width,c.height);x.drawImage(im,0,0);items.forEach((s,i)=>{if(!s.visible||!s.mask)return;x.save();x.beginPath();s.mask.forEach((p,j)=>j?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();x.fillStyle=rgba(s.color,.18);x.fill();x.strokeStyle=s.color;x.lineWidth=stroke;x.stroke();let p=s.mask[0];x.font='bold 25px Arial';let t=s.label||String(i+1),w=x.measureText(t).width+14;x.fillStyle=s.color;x.fillRect(p.x,p.y-31,w,31);x.fillStyle=s.color==='#fff'?'#222':'#fff';x.fillText(t,p.x+7,p.y-8);x.restore()})}
function list(){let l=document.getElementById('list');document.getElementById('cnt').textContent='('+items.length+')';l.innerHTML='';if(!items.length){l.innerHTML='<div class="empty">사진에서 홀드를 클릭하면<br>선택 결과가 여기에 표시됩니다.</div>';return}items.forEach((s,i)=>{let d=document.createElement('div');d.className='card';let th=document.createElement('canvas');th.className='thumb';th.width=58;th.height=58;if(s.mask){let q=th.getContext('2d'),xs=s.mask.map(p=>p.x),ys=s.mask.map(p=>p.y),a=Math.min(...xs),b=Math.max(...xs),u=Math.min(...ys),v=Math.max(...ys),sc=Math.min(46/(b-a||1),46/(v-u||1));q.beginPath();s.mask.forEach((p,j)=>{let xx=29+(p.x-(a+b)/2)*sc,yy=29+(p.y-(u+v)/2)*sc;j?q.lineTo(xx,yy):q.moveTo(xx,yy)});q.closePath();q.fillStyle=rgba(s.color,.2);q.fill();q.strokeStyle=s.color;q.lineWidth=3;q.stroke()}let m=document.createElement('div');m.className='meta';m.innerHTML='선택 '+(i+1);let inp=document.createElement('input');inp.value=s.label;inp.oninput=e=>{s.label=e.target.value;draw()};m.appendChild(inp);let b=document.createElement('button');b.textContent='⌫';b.onclick=()=>{items.splice(i,1);current=items.at(-1)||null;list();draw()};d.append(th,m,b);l.appendChild(d)})}
document.getElementById('reset').onclick=document.getElementById('delall').onclick=()=>{items=[];current=null;list();draw()};
function out(){let o=document.createElement('canvas');o.width=im.naturalWidth;o.height=im.naturalHeight;let q=o.getContext('2d');q.drawImage(im,0,0);items.forEach((s,i)=>{if(!s.mask||!s.visible)return;q.save();q.beginPath();s.mask.forEach((p,j)=>j?q.lineTo(p.x,p.y):q.moveTo(p.x,p.y));q.closePath();q.fillStyle=rgba(s.color,.18);q.fill();q.strokeStyle=s.color;q.lineWidth=stroke;q.stroke();let p=s.mask[0];q.font='bold 26px Arial';let t=s.label||String(i+1),w=q.measureText(t).width+16;q.fillStyle=s.color;q.fillRect(p.x,p.y-34,w,34);q.fillStyle=s.color==='#fff'?'#222':'#fff';q.fillText(t,p.x+8,p.y-9);q.restore()});return o}document.getElementById('saveR').onclick=()=>{let a=document.createElement('a');a.download='cracker-hold-result.png';a.href=out().toDataURL('image/png');a.click()};
function modal(t,p){document.getElementById('mt').textContent=t;document.getElementById('mp').textContent=p;document.getElementById('modal').classList.remove('hidden')}document.getElementById('mc').onclick=()=>document.getElementById('modal').classList.add('hidden');document.getElementById('help').onclick=()=>modal('사용 방법','선택 모드에서 홀드 내부를 클릭하면 SAM3가 외곽선을 찾습니다.\n\n영역 추가: 빠진 부분을 클릭\n영역 제외: 잘못 포함된 부분을 클릭\n\n마지막으로 결과 이미지 저장(PNG)을 누르면 원본 사진 위에 선택된 홀드와 번호/라벨이 표시된 결과물을 저장합니다.');
